root = "."

# Exclude unnecessary directories
ignore = ["tmp", "vendor", "node_modules", ".git", "logs"]

# Watch Go files and restart on change
[[watch]]
path = "."
includes = ["*.go", "**/*.go"]

# Watch HTML template files and restart Air when changed
[[watch]]
path = "views"
includes = ["*.html", "**/*.html"]

# Watch assets (CSS, JS, images) and restart Air when changed
[[watch]]
path = "assets"
includes = ["*"]
cmd = "go run main.go"  # ✅ Restart on static file changes

# Build command (restart Air when a file changes)
cmd = "go run main.go"

log = "air.log"
color = true
