root = "."

# Exclude these directories
ignore = ["tmp", "vendor", "node_modules", ".git", "logs"]

# Watch Go files and restart on change
[[watch]]
path = "."
includes = ["*.go", "**/*.go", "**/*.tmpl"]
excludes = ["tmp/*", "vendor/*"]

# Watch static assets (CSS, JS, images) but restart is not needed
[[watch]]
path = "assets"
includes = ["*"]
cmd = ""  # No restart for static files

# Watch HTML templates but don't restart Air on change
[[watch]]
path = "views"
includes = ["*.html", "**/*.html"]
excludes = []  # ✅ Ignore temporary files (~ files created by editors)
cmd = "echo 'HTML file changed, but no restart needed'"  # ✅ Prevents Air restart

# Build command
cmd = "go run main.go"

log = "air.log"
color = true