# File: .air.toml

root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
bin = "tmp/main.exe"
cmd = "go build -o ./tmp/main.exe ."
delay = 1000
exclude_dir = ["tmp", "testdata", ".vscode"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
include_dir = ["assets", "config", "controllers", "helpers", "middlewares", "models", "routes", "views"]
include_ext = ["go", "tpl", "tmpl", "html"]
include_file = []
log = "build-errors.log"
poll = false
poll_interval = 0
post_cmd = []
pre_cmd = []
send_interrupt = true
stop_on_error = false
kill_delay = "0s"

[color]
app = "cyan"
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
silent = false
time = true

[misc]
clean_on_exit = true

[proxy]
enabled = false
app_port = 8080
proxy_port = 3000

[screen]
clear_on_rebuild = true
keep_scroll = true
